### ISSUE TITLE
white

### ISSUE THREAD

**Issue by JustSpaceisded** [cool-void-zero/cool-void-zero#1]
do you want help with it being dark mode or do you want to be blind :)

**Comment by JustSpaceisded** [comment]
or do you just like white bc you are insane

**Comment by cool-tien** [comment]
Thanks for remind, I changed.

JustSpace ***@***.***> 於 2023年5月17日 週三 下午9:47寫道：

**Comment by cool-tien** [comment]
Thanks for remind, I changed. :)

**Comment by JustSpaceisded** [comment]
np
